name: CMake on multiple platforms

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    env:
      IS_CI: 1
      IS_CPU_CI: 1
      LSAN_OPTIONS: suppressions=${{ github.workspace }}/.github/workflows/lsan.supp
      PCCL_LOG_LEVEL: DEBUG  # Global log level set to DEBUG

    strategy:
      fail-fast: false

      matrix:
        include:
          # Linux configurations using self-hosted runners
          - runs-on: [ self-hosted, Linux, X64, cpu ]
            os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            is_host_arch: true
            generator: Ninja
            build_type: Release
            pccl_build_cuda_support: OFF

          - runs-on: [ self-hosted, Linux, X64, cuda ]
            os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            is_host_arch: true
            generator: Ninja
            build_type: Release
            pccl_build_cuda_support: ON

          # Windows configurations using GitHub-hosted runners
          # x86_64, no cuda
          - runs-on: [ self-hosted, Windows, X64, cpu ]
            os: windows-latest
            msvc_cpu_arch: amd64
            is_host_arch: true
            make_program: C:/Program Files/NinjaBuild/bin/ninja.exe
            generator: Ninja
            build_type: Release
            pccl_build_cuda_support: OFF

          # x86_64 with cuda
          - runs-on: [ self-hosted, Windows, X64, cuda ]
            os: windows-latest
            msvc_cpu_arch: amd64
            is_host_arch: true
            make_program: C:/Program Files/NinjaBuild/bin/ninja.exe
            generator: Ninja
            build_type: Release
            pccl_build_cuda_support: ON

          # aarch64, no cuda
          - runs-on: [ self-hosted, Windows, X64, cpu ]
            os: windows-latest
            msvc_cpu_arch: amd64_arm64 # cross compile arm64 on x86_64
            is_host_arch: false
            make_program: C:/Program Files/NinjaBuild/bin/ninja.exe
            generator: Ninja
            build_type: Release
            pccl_build_cuda_support: OFF

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set reusable strings (Unix)
        id: strings-unix
        if: runner.os != 'Windows'
        shell: bash
        run: |
          build_output_dir="${{ github.workspace }}/build"
          echo "build-output-dir=$build_output_dir" >> "$GITHUB_OUTPUT"
      
      - name: Set reusable strings (Windows)
        id: strings-windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $build_output_dir = "${{ github.workspace }}/build"
          echo "build-output-dir=$build_output_dir" >> $env:GITHUB_OUTPUT
      
      - name: Configure CMake (Unix)
        if: runner.os != 'Windows'
        run: >
          cmake -B ${{steps.strings-unix.outputs.build-output-dir }}
          -G "${{ matrix.generator }}"
          "-DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}"
          "-DCMAKE_C_COMPILER=${{ matrix.c_compiler }}"
          "-DCMAKE_BUILD_TYPE=${{ matrix.build_type }}"
          "-DPCCL_BUILD_CUDA_SUPPORT=${{ matrix.pccl_build_cuda_support }}"
          -S "${{ github.workspace }}"
      
      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_cpu_arch }}
          cmake -B ${{steps.strings-windows.outputs.build-output-dir }} -G ${{ matrix.generator }} "-DCMAKE_MAKE_PROGRAM=${{ matrix.make_program }}" "-DPCCL_BUILD_CUDA_SUPPORT=${{ matrix.pccl_build_cuda_support }}" -S "${{ github.workspace }}"

      - name: Build (Unix)
        if: runner.os != 'Windows'
        run: cmake --build ${{ steps.strings-unix.outputs.build-output-dir }} --config ${{ matrix.build_type }} --parallel

      - name: Build (Windows)
        shell: cmd
        if: runner.os == 'Windows'
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_cpu_arch }}
          cmake --build "${{ steps.strings-windows.outputs.build-output-dir }}" --config ${{ matrix.build_type }} --parallel

      - name: Test
        if: ${{ matrix.is_host_arch }}
        working-directory: ${{ steps.strings-unix.outputs.build-output-dir || steps.strings-windows.outputs.build-output-dir }}
        run: ctest --verbose --build-config ${{ matrix.build_type }} --output-on-failure

      - name: Compile Python wheel (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_cpu_arch }}
          set MAKE_PROGRAM=${{ matrix.make_program }}
          set CMAKE_GENERATOR=${{ matrix.generator }}
          set PCCL_BUILD_CUDA_SUPPORT=${{ matrix.pccl_build_cuda_support }}
          cd ${{ github.workspace }}/python/framework && pip3 wheel --verbose -w dist .
      
      - name: Compile Python wheel (Unix)
        if: runner.os != 'Windows'
        run: cd ${{ github.workspace }}/python/framework && CMAKE_GENERATOR=${{ matrix.generator }} PCCL_BUILD_CUDA_SUPPORT=${{ matrix.pccl_build_cuda_support }} pip3 wheel --verbose -w dist .

      - name: Create Python virtual environment (Unix)
        if: ${{ runner.os != 'Windows' && matrix.is_host_arch }}
        run: python3 -m venv ${{ github.workspace }}/venv
      
      - name: Create Python virtual environment (Windows)
        if: ${{ runner.os == 'Windows' && matrix.is_host_arch }}
        run: python -m venv ${{ github.workspace }}/venv

      - name: Activate virtual environment (Unix)
        if: ${{ runner.os != 'Windows' && matrix.is_host_arch }}
        run: echo 'PATH=${{ github.workspace }}/venv/bin:$PATH' >> $GITHUB_ENV

      - name: Activate virtual environment (Windows)
        if: ${{ runner.os == 'Windows' && matrix.is_host_arch }}
        shell: powershell
        run: |
          echo "${{ github.workspace }}\venv\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      
      - name: Install wheel (Windows)
        if: ${{ runner.os == 'Windows' && matrix.is_host_arch }}
        shell: pwsh
        run: |
          $wheels = Get-ChildItem "$env:GITHUB_WORKSPACE\python\framework\dist\pccl-*.whl"
          if (-Not $wheels) {
            Write-Error "No .whl files found!"
            exit 1
          }
          pip install $wheels

      - name: Install wheel (Unix)
        if: ${{ runner.os != 'Windows' && matrix.is_host_arch }}
        shell: bash
        run: |
          python -m pip install ./python/framework/dist/pccl-*.whl

      - name: Install Unit Test dependencies
        if: ${{ matrix.is_host_arch }}
        run: python -m pip install -r ${{ github.workspace }}/python/tests/unit_tests/requirements.txt

      - name: Python Unit Tests
        if: ${{ matrix.is_host_arch }}
        run: python -m pytest -s ${{ github.workspace }}/python/tests/unit_tests

      - name: Install Numpy-Only Test dependencies
        if: ${{ matrix.is_host_arch }}
        run: python -m pip install -r ${{ github.workspace }}/python/tests/numpy_only_tests/requirements.txt

      - name: Uninstall pytorch for Numpy-Only Tests
        if: ${{ matrix.is_host_arch }}
        run: python -m pip uninstall -y torch torchvision

      - name: Python Numpy-Only Tests
        if: ${{ matrix.is_host_arch }}
        run: python -m pytest -s -v ${{ github.workspace }}/python/tests/numpy_only_tests

      - name: Install Pytorch-Only Test dependencies
        if: ${{ matrix.is_host_arch }}
        run: python -m pip install -r ${{ github.workspace }}/python/tests/pytorch_only_tests/requirements.txt

      - name: Uninstall numpy for Pytorch-Only Tests
        if: ${{ matrix.is_host_arch }}
        run: python -m pip uninstall -y numpy

      - name: Python Pytorch-Only Tests
        if: ${{ matrix.is_host_arch }}
        run: python -m pytest -s -v ${{ github.workspace }}/python/tests/pytorch_only_tests

      - name: Install End-to-End Test dependencies
        if: ${{ matrix.is_host_arch }}
        run: |
          python -m pip install -r ${{ github.workspace }}/python/tests/end_to_end/requirements.txt
          python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126

      - name: Python End-to-End Tests
        if: ${{ matrix.is_host_arch }}
        working-directory: ${{ github.workspace }}/python/tests/end_to_end/
        run: python -m pytest -s -v ${{ github.workspace }}/python/tests/end_to_end